name: scheduled data processing

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:     # Manual trigger for testing or on-demand processing

jobs:
  run-data-processing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then 
          pip install -r requirements.txt || { echo "Dependency installation failed"; exit 1; }
        fi

    - name: Delete previous files with prefix 'quakes_'
      run: |
        echo "Deleting previous parquet files..."
        DELETED_FILES=$(find data/ -name 'quakes_*.parquet' -exec rm {} \; -print)
        if [ -z "$DELETED_FILES" ]; then
          echo "No files with prefix 'quakes_' found."
        else
          echo "Deleted files: $DELETED_FILES"
        fi

    - name: Run data processing script
      run: |
        echo "Starting data processing script..."
        set -e 
        python src/data_processing.py || { echo "Data processing failed"; exit 1; }
        echo "Data processing completed successfully."

    # - name: Commit and push the processed data
    #   if: success() 
    #   run: |
    #     echo "Committing and pushing processed data..."
    #     git config --global user.name "github actions"
    #     git config --global user.email "actions@github.com"
    #     git add data/
    #     git diff --quiet && git diff --staged --quiet || git commit -m "Update processed data on $(date +'%y-%m-%d %H:%M:%S')"
    #     git push || { echo "Git push failed"; exit 1; }
    #   env:
    #     github_token: ${{ secrets.github_token }}
    #
    # - name: Send Slack notification on success
    #   if: success()
    #   uses: 8398a7/action-slack@v3
    #   with:
    #     status: success
    #   env:
    #     slack_webhook_url: ${{ secrets.slack_webhook_url }}
    #
    # - name: Send Slack notification on failure
    #   if: failure()
    #   uses: 8398a7/action-slack@v3
    #   with:
    #     status: failure
    #   env:
    #     slack_webhook_url: ${{ secrets.slack_webhook_url }}
