name: scheduled data processing

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:     # Manual trigger for testing or on-demand processing

jobs:
  run-data-processing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then 
          pip install -r requirements.txt
        fi
        
    - name: Delete previous files with prefix 'quakes_'
      run: |
        deleted_files=$(find data/ -name 'quakes_*.parquet' -exec rm {} \; -print)
        fi
      continue-on-error: true

    - name: Run data processing script
      run: |
        python src/data_processing.py
